name: E2E Testing for Kokesa Booking App

on: [push]

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment (version 20)
      - name: Set up Node.js (v20)
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install dependencies using npm
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Cypress tests with recording enabled
      - name: Run Cypress Tests with Recording
        uses: cypress-io/github-action@v4 # Updated to version v4
        with:
          build: npm run build # Build the Next.js app
          start: npm run start # Start the Next.js app
          wait-on: "http://localhost:3000" # Wait until the app is ready before running tests
          record: true # Enable test recording

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # Securely pass the Cypress Record Key from GitHub Secrets
