name: Unit testing for kokesa

on:["push"]
jobs:
  NextJS-Tests:
    name: Unit testing for kokesa
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Run Jest tests
        run: npm test
